name: Deploy to s3
on:
  push:
    branches:
      - main
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: deploy-s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://atoz.codes --delete --exclude ".github/*" --exclude ".git/*" --exclude ".vscode/*" --exclude "node_modules/*" --exclude "README.md" --exclude "LICENSE" --exclude "package.json" --exclude "package-lock.json" --exclude "yarn.lock" --exclude "Dockerfile" --exclude "Dockerfile.dev" --exclude "docker-compose.yml" --exclude "nginx" --exclude ".DS_Store"
